/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IntersenseDump */

#ifndef _Included_IntersenseDump
#define _Included_IntersenseDump
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IntersenseDump
 * Method:    addRotListener
 * Signature: (LVrpnTracker/RotListener;)V
 */
JNIEXPORT void JNICALL Java_IntersenseDump_addRotListener
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
