/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VrpnTracker_RotListener */

#ifndef _Included_VrpnTracker_RotListener
#define _Included_VrpnTracker_RotListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
