/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VrpnTracker */

#ifndef _Included_VrpnTracker
#define _Included_VrpnTracker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
