/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VrpnTracker_PosListener */

#ifndef _Included_VrpnTracker_PosListener
#define _Included_VrpnTracker_PosListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
